version: '3.8'

services:
  postgres:
    image: postgres:14.10-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: im_lazy
    ports:
      - "5432:5432"