server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/im_lazy

  jpa:
    show-sql: true

  flyway:
    enabled: true
